In [5]:
import numpy as np

In [6]:
# Create an array with 2 dimensions

In [16]:
a = np.array([1, 2, 3, 4], ndmin=2) # ndmin specifies # of dimensions
print(f"{a}\nShape: {a.ndim}") # ndim = # dimensions

[[1 2 3 4]]
Shape: 2


In [ ]:
#%#%#%#%#%#%#%#%#%#
# indexing arrays
#%#%#%#%#%#%#%#%#%#

In [40]:
a = np.array([1,2,3,4,5])

In [41]:
# Print the first item in the array
print(a[0])

1


In [43]:
# Print the last item in the array
print(a[-1])

5


In [44]:
a = np.array([[10,20,30,40],[50,60,70,80]])

In [45]:
# Print the number 50 from the array
print(a[1,0])

50


In [46]:
#%#%#%#%#%#%#%#%#%#
# slicing arrays
#%#%#%#%#%#%#%#%#%#

In [48]:
a = np.array([10,15,20,25,30,35,40])

In [49]:
# Insert the correct slicing syntax to print the following selection:

In [59]:
# Slice from (including) the second item to (not including) the fifth item
print(a[1:4]) # 15-25

[15 20 25]


In [60]:
# Slice from (including) the third item to (not including) the fifth item
print(a[2:4])# 20-25

[20 25]


In [61]:
# Slice every other item from (including) the second item
# to (not including) the fifth item.

In [64]:
print(a[1:5:2])

[15 25]


In [ ]:
# Slice every other item from the entire array

In [65]:
print(a[::2])

[10 20 30 40]


In [66]:
#%#%#%#%#%#%#%#%#%#
# data types
#%#%#%#%#%#%#%#%#%#

In [67]:
# i = integer
# b = boolean
# u = unsigned integer
# f = float
# c = complex float
# m = timedelta
# M = datatime
# O = object
# S = string

In [68]:
# Insert the correct NumPy syntax to print the data type of an array.

In [69]:
a = np.array([1,2,3,4])

In [70]:
print(a.dtype)

int64


In [71]:
# Insert the correct argument to specify 
# that the array should be of type STRING.

In [73]:
a = np.array([1,2,3,4], dtype='S')
print(a.dtype)

|S1


In [74]:
# Insert the correct method to change the data type to integer.

In [75]:
a = arr.astype('i')
print(a.dtype)

int32


In [76]:
#%#%#%#%#%#%#%#%#%#
# copy vs view
#%#%#%#%#%#%#%#%#%#

In [77]:
a = np.array([1,2,3,4,5])

In [78]:
# Make a copy of the array

In [84]:
c = a.copy() # copy is a new array
print(c)

[1 2 3 4 5]


In [83]:
# Make a view of the array
v = a.view() # view of the original array
print(v)

[1 2 3 4 5]
