In [1]:
# NumPy Tutorial - Python Engineer

In [2]:
import numpy as np

In [3]:
# NumPy Array

In [4]:
a = np.array([1,2,3,4,5])

print(a)
print(a.shape) # Shape of the array
print(a.dtype) # Type of the element
print(a.ndim) # Number of dimensions
print(a.size) # Total number of elements
print (a.itemsize) # Size of bytes in each element

[1 2 3 4 5]
(5,)
int64
1
5
8


In [5]:
##################

##################

In [6]:
# Essential Methods

In [7]:
# Access and change the elements

print(a[0])

1


In [8]:
a[0] = 5

print(a[0])

5


In [9]:
print(a)

[5 2 3 4 5]


In [10]:
# Changed the first element from 1 to 5

In [11]:
# Math operations with elements

In [12]:
b = a * np.array([2,0,2,0,2])

In [13]:
print(b) # Print results of math operation above

[10  0  6  0 10]


In [14]:
print(b.sum()) # Sum of numbers in array b

26


In [15]:
##################

##################

In [16]:
# NumPy Array vs List

In [17]:
l = [1,2,3]
a = np.array([3,2,1]) # Creates an array from a list

In [18]:
print(f"List\n{l}")
print(f"Array\n{a}")

List
[1, 2, 3]
Array
[3 2 1]


In [19]:
# Multiply *

In [20]:
l2 = 2 * l # List repeated 2 times, same as l+l
print(l2)

[1, 2, 3, 1, 2, 3]


In [21]:
# The list will repeat itself however many times it is mulitplied

In [22]:
a2 = 2 * a # Multplication for each element
print(a2)

[6 4 2]


In [23]:
# Note: Function applied to array usually applies to each element

In [24]:
##################

##################

In [25]:
# Dot Product

In [26]:
a = np.array([1,2])
b = np.array([3,4])

In [27]:
# Manual way for solving Dot Product
dot = 0
for i in range(len(a)):
    dot += a[i] * b[i]
print(dot)

11


In [28]:
# NumPy way for solving Dot Product
dot2 = np.dot(a,b)
print(dot2)

11


In [29]:
# Instance method for solving Dot Product
dot3 = a.dot(b)
print(dot3)

11


In [30]:
# Newer versions let you use @ sign
dot4 = a @ b
print(dot)

11


In [31]:
##################

##################

In [32]:
# Python List vs NumPy Array Speed Test

In [33]:
from timeit import default_timer as timer
a = np.random.randn(1000)
b = np.random.randn(1000)

a2 = list(a)
b2 = list(b)
t = 1000

In [34]:
def dot1(): # Python way
    dot = 0
    for i in range(len(a2)):
        dot += a2[i] * b2[i]
    return dot

def dot2(): # NumPy way
    return np.dot(a,b)

# Timers
start = timer()

for i in range(t): # Timer for dot1()
    dot1()
end = timer()
t1 = end-start

for i in range(t): # Timer for dot2()
    dot2()
end = timer()
t2 = end-start

In [35]:
print(f"Python list timer: {t1}\nNumPy array timer: {t2}\nRatio: {t1/t2}")

Python list timer: 0.17172579199999993
NumPy array timer: 0.17308308300000008
Ratio: 0.9921581533187727


In [36]:
##################

##################

In [37]:
# Multi-dimensional or Matrix Array

In [38]:
a = np.array([[1,2], [3,4]])

In [39]:
print(a)

[[1 2]
 [3 4]]


In [40]:
print(a.shape)

(2, 2)


In [41]:
# Access elements
# Row first, then column
print(f"Example Array:\n{a}\n")

# Option a[0]
print(f"a[0]\n{a[0]}\n")

# Same as a[0][0]
print(f"a[0][0]\n{a[0][0]}\n")

# or a[0,0]
print(f"a[0,0]\n{a[0,0]}")

Example Array:
[[1 2]
 [3 4]]

a[0]
[1 2]

a[0][0]
1

a[0,0]
1


In [42]:
# Slicing
print(f"Example Array:\n{a}\n")

print(f"Rows\n{a[:,0]}\n") # All rows in col 0 - a[:,0]
print(f"Columns\n{a[0,:]}") # All columns in row 0 - a[0,:]

Example Array:
[[1 2]
 [3 4]]

Rows
[1 3]

Columns
[1 2]


In [43]:
# Transpose Matrix

In [44]:
print(a.T) # Original [[1 2]
#                     [3 4]]

[[1 3]
 [2 4]]


In [45]:
# Matrix Multiply *

In [46]:
b = np.array([[3,4],[5,6]])
c = a.dot(b) # Calculating dot product
d = a * b # Elements will multiply

In [47]:
print(f"Array 'a'\n{a}\n")

print(f"Array 'b'\n{b}\n")

print(f"Dot Product\n{c}\n")

print(f"Elementwise Multiplication\n{d}")

Array 'a'
[[1 2]
 [3 4]]

Array 'b'
[[3 4]
 [5 6]]

Dot Product
[[13 16]
 [29 36]]

Elementwise Multiplication
[[ 3  8]
 [15 24]]


In [48]:
# Determinant

In [49]:
c = np.linalg.det(a) # linalg is for the Linear Algebra package
print(c)

-2.0000000000000004


In [50]:
# Inverse

In [51]:
c = np.linalg.inv(a)
print(c)

[[-2.   1. ]
 [ 1.5 -0.5]]


In [52]:
# Diagnoal / diag

In [53]:
c = np.diag(a)
print(f"Original array\n{a}\n")
print(f"Diag array\n{c}")

Original array
[[1 2]
 [3 4]]

Diag array
[1 4]


In [54]:
##################

##################

In [55]:
# Indexing, Slicing & Boolean Indexing
# Slicing: Similar to Python lists, NumPy arrays can be sliced
# Since arrays are multidimensional, you must specify
# for the dimension of the array:

In [56]:
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [57]:
# Int array indexing
b = a[0,1] # row 0, column 1
print(b)

2


In [58]:
# Slicing
row0 = a[0,:] # row 0, all columns
print(row0)

[1 2 3 4]


In [59]:
col0 = a[:,0] # all rows, column 0
print(col0)

[1 5 9]


In [60]:
slice_a = a[0:2,1:3] # -
print(slice_a)

[[2 3]
 [6 7]]


In [61]:
# Indexing starting from the end (-1, -2)
last = a[-1,-1] # prints the last element in the array
print(last)

12


In [62]:
# Boolean index
a = np.array([[1,2],[3,4],[5,6]])
print(a)

[[1 2]
 [3 4]
 [5 6]]


In [63]:
# same shape with True or False for the condition
bool = a > 2 # checks each element and returns true/false
print(bool)

[[False False]
 [ True  True]
 [ True  True]]


In [64]:
print(a[bool]) # returns all true elements

[3 4 5 6]


In [65]:
##################

##################

In [66]:
# Reshaping - 1D Array

In [67]:
a = np.arange(1,7)
print(a)

[1 2 3 4 5 6]


In [68]:
b = a.reshape(2,3) # makes array with: 2 rows, 3 cols
print(b)

[[1 2 3]
 [4 5 6]]


In [69]:
c = a.reshape(3,2) # 3 rows, 3 cols
print(c)

[[1 2]
 [3 4]
 [5 6]]


In [70]:
d = a.reshape(2,4) # should give error

ValueError: cannot reshape array of size 6 into shape (2,4)

In [ ]:
# newaxis function is used to create a new axis in the data
# needed when model requires the data to be shaped in
# a specific manner.

In [71]:
print(f"{a}\na.shape\n{a.shape}")

[1 2 3 4 5 6]
a.shape
(6,)


In [72]:
d = a[np.newaxis, :]
print(f"{d}\n{d.shape}") # ML (machine learning models) 
#                          expect data in this format

[[1 2 3 4 5 6]]
(1, 6)


In [73]:
##################

##################

In [74]:
# Concatenation

In [80]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])

print(f"array 'a'\n{a}\narray 'b'\n{b}")

array 'a'
[[1 2]
 [3 4]]
array 'b'
[[5 6]
 [7 8]]


In [150]:
# combine into 1-dimensional array
c = np.concatenate((a,b), axis=None) # axis=None is same as default

In [149]:
print(f"{a}\n\n{b}\n\ne 'combine a,b':\n{e}")

[1 2 3]

[42  2  3]

e 'combine a,b':
[[1 2 5 7]
 [3 4 6 8]]


In [83]:
# add a new row using axis=0

In [84]:
d = np.concatenate((a,b),axis=0) # axis=0 adds a new row

In [101]:
print(f"{a}\n\n{b}\n\nd 'add new row':\n{d}")

[[1 2]
 [3 4]]

[[5 6]
 [7 8]]

d 'add new row':
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [86]:
# add a new col using axis=1

In [103]:
e = np.concatenate((a,b.T),axis=1) # b must be transposed (.T)

In [102]:
print(f"{a}\n\n{b}\n\ne 'add new col':\n{e}")

[[1 2]
 [3 4]]

[[5 6]
 [7 8]]

e 'add new col':
[[1 2 5 7]
 [3 4 6 8]]


In [104]:
##################

##################

In [105]:
# Broadcasting

In [107]:
a = np.array([[1,2,3],[4,5,6],[10,11,12]])
b = np.array([1,0,1])

c = a + b # add 'b' to each row of 'a' using broadcasting
print(c)

[[ 2  2  4]
 [ 5  5  7]
 [11 11 13]]


In [108]:
##################

##################

In [116]:
# Functions & Axis

a = np.array([[7,8,9,10,11,12,13],[17,18,19,20,21,22,23]])
print(a)

[[ 7  8  9 10 11 12 13]
 [17 18 19 20 21 22 23]]


In [ ]:
# Add / sum

In [117]:
print(f"a.sum()\n{a.sum()}") # default=None, if not specified

a.sum()
210


In [118]:
print(f"a.sum(axis=None)\n{a.sum(axis=None)}") # overall sum

a.sum(axis=None)
210


In [119]:
print(f"a.sum(axis=0)\n{a.sum(axis=0)}") # sum along the rows

a.sum(axis=0)
[24 26 28 30 32 34 36]


In [120]:
print(f"a.sum(axis=1)\n{a.sum(axis=1)}") # sum along the cols

a.sum(axis=1)
[ 70 140]


In [ ]:
# Average / mean

In [122]:
print(f"a.mean()\n{a.mean()}") # default=None, if not specified

a.mean()
15.0


In [125]:
print(f"a.mean(axis=None)\n{a.mean(axis=None)}") # overall mean

a.mean(axis=None)
15.0


In [127]:
print(f"a.mean(axis=0)\n{a.mean(axis=0)}") # 1 mean entry for each col

a.mean(axis=0)
[12. 13. 14. 15. 16. 17. 18.]


In [128]:
print(f"a.mean(axis=1)\n{a.mean(axis=1)}") # 1 mean entry for each row

a.mean(axis=1)
[10. 20.]


In [129]:
# more options: std, var, min, max

In [130]:
##################

##################

In [131]:
# Copying
# - be careful with copying -

In [142]:
a = np.array([1,2,3])
b = a.copy() # only copies reference

print(f"a: {a}\nb: {b}")

a: [1 2 3]
b: [1 2 3]


In [145]:
b[0] = 42 # only changes copy

print(f"a: {a}\nb: {b}")

a: [1 2 3]
b: [42  2  3]


In [ ]:
##################

##################